name: docs-check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build docs
        uses: ./.github/actions/build-docs

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: docs-html
          path: doc/build/html
          if-no-files-found: error
